---
# handlers file for careerleaf-log-courier
- name: restart log-courier
  service:
    state: restarted
    name: log-courier

- name: reload monit
  service:
    name: monit
    state: reloaded
  ignore_errors: yes
